"""Rename column

Revision ID: 24b94a4887bc
Revises: 40091d9d5f39
Create Date: 2014-10-10 16:31:33.867043

"""

# revision identifiers, used by Alembic.
revision = '24b94a4887bc'
down_revision = '40091d9d5f39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('name', sa.String(length=50), nullable=True))
    op.drop_column('auto', 'text')
    op.alter_column('individual', 'auto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('individual', 'auto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('auto', sa.Column('text', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('auto', 'name')
    ### end Alembic commands ###
