"""Added individuals table

Revision ID: 2a45b9504d0b
Revises: None
Create Date: 2014-10-07 10:34:05.587025

"""

# revision identifiers, used by Alembic.
revision = '2a45b9504d0b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=50), nullable=False),
    sa.Column('lname', sa.String(length=50), nullable=False),
    sa.Column('oname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('individual')
    ### end Alembic commands ###
