"""Type 'str' for return_date, temporarily

Revision ID: 2d6e526f5590
Revises: 2908f6dcd670
Create Date: 2014-11-13 15:34:01.488242

"""

# revision identifiers, used by Alembic.
revision = '2d6e526f5590'
down_revision = '2908f6dcd670'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_book', 'return_date',
               existing_type=sa.DATE(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_book', 'return_date',
               existing_type=sa.DATE(),
               nullable=False)
    ### end Alembic commands ###
