"""Added auto table

Revision ID: 40091d9d5f39
Revises: 2a45b9504d0b
Create Date: 2014-10-07 11:10:50.266834

"""

# revision identifiers, used by Alembic.
revision = '40091d9d5f39'
down_revision = '2a45b9504d0b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ## commands auto generated by Alembic - please adjust! ###
    op.create_table('auto',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        u'individual',
        sa.Column('auto_id', sa.Integer(), sa.ForeignKey('auto.id'), nullable=True)
    )
    ### end Alembic commands ###


def downgrade():
    # ## commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'individual', 'auto_id')
    op.drop_table('auto')
    ### end Alembic commands ###
