"""Added flag is_super in role

Revision ID: 653a5904ce
Revises: 571bdb4bfe0
Create Date: 2014-12-01 17:31:25.652306

"""

# revision identifiers, used by Alembic.
revision = '653a5904ce'
down_revision = '571bdb4bfe0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super', sa.Boolean(), nullable=False))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('is_super')

    ### end Alembic commands ###
