"""Added account table

Revision ID: 928a5711f9e
Revises: 24b94a4887bc
Create Date: 2014-10-27 16:13:50.278865

"""

# revision identifiers, used by Alembic.
revision = '928a5711f9e'
down_revision = '24b94a4887bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=50), nullable=False),
    sa.Column('lname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), sa.ForeignKey('book.id'), nullable=False),
    sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.id'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], [u'book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), sa.ForeignKey('author.id'), nullable=False),
    sa.Column('book_id', sa.Integer(), sa.ForeignKey('book.id'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], [u'author.id'], ),
    sa.ForeignKeyConstraint(['book_id'], [u'book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author_book')
    op.drop_table('user_book')
    op.drop_table('user')
    op.drop_table('author')
    op.drop_table('book')
    ### end Alembic commands ###
