"""Added session table

Revision ID: a0e2a693e8
Revises: 2d6e526f5590
Create Date: 2014-11-26 11:32:34.980081

"""

# revision identifiers, used by Alembic.
revision = 'a0e2a693e8'
down_revision = '2d6e526f5590'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barsup_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('web_session_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('web_session_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barsup_session')
    ### end Alembic commands ###
