"""Remove constraints for email & password

Revision ID: f9e034438f
Revises: 290d8fb7e8
Create Date: 2015-02-10 11:37:58.404655

"""

# revision identifiers, used by Alembic.
revision = 'f9e034438f'
down_revision = '290d8fb7e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    ### end Alembic commands ###
